# AI

# OpenAI
quarkus.langchain4j.openai.api-key=${OPENAI_API_KEY}
quarkus.langchain4j.openai.chat-model.model-name=gpt-4o-mini
quarkus.langchain4j.openai.chat-model.log-requests=false
quarkus.langchain4j.openai.chat-model.log-responses=false
quarkus.langchain4j.openai.timeout=120s

# Claude
quarkus.langchain4j.anthropic.api-key=${ANTHROPIC_API_KEY}

# Gemini
quarkus.langchain4j.ai.gemini.api-key=${GEMINI_API_KEY}
quarkus.langchain4j.ai.gemini.log-requests=true
quarkus.langchain4j.ai.gemini.log-responses=true
quarkus.langchain4j.ai.gemini.timeout=120s
quarkus.langchain4j.ai.gemini.chat-model.log-requests=true
quarkus.langchain4j.ai.gemini.chat-model.log-responses=true

# Watson
# TODO

#---

# Chat memory - increase window for multi-step tool execution
quarkus.langchain4j.chat-memory.memory-window.max-messages=50

# Logging
quarkus.log.category."dev.langchain4j".level=WARN
quarkus.log.category."io.quarkiverse.langchain4j".level=WARN

# Tempo MCP client
#quarkus.langchain4j.mcp.tempo.transport-type=streamable-http
#quarkus.langchain4j.mcp.tempo.url=${tempo-mcp.endpoint}/api/mcp

# Grafana MCP process
#quarkus.langchain4j.mcp.grafana.transport-type=stdio
#quarkus.langchain4j.mcp.grafana.command=uvx,mcp-grafana
#quarkus.langchain4j.mcp.grafana.environment.GRAFANA_URL=${grafana.endpoint}